name: dependent job
on: push

jobs:
  job_on_ubuntu:
    runs-on: ubuntu-latest
    name: Job on Ubuntu
    steps:
      - run: date
  job_on_macos:
    needs: [job_on_ubuntu]
    runs-on: macos-latest
    name: A job that runs on mac after ubuntu
    steps:
      - run: pwd
      - name: a new step
        run: ls
  final-job:
    needs: [job_on_macos]
    runs-on: ubuntu-latest
    name: A final job
    steps:
      - run: echo Hello World!
  
        
    
  
    
